version: '3.8'
services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://userdev:passdev@db:5432/dutydb
  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdev
      POSTGRES_PASSWORD: passdev
      POSTGRES_DB: dutydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
